View(iris)
summary(iris)
class(iris)
typeof(iris)
head(iris, 6)
tail(iris, 5)

str(iris)
View(iris)
iris$Petal.Width <- factor(iris$Petal.Width)
str(iris)
class(iris$Petal.Width)
iris$Petal.Width <- as.numeric(iris$Petal.Width)
str(iris)
